import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const pack=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const root=path.resolve(pack,'../../..');
const source=fs.readFileSync(path.join(root,'web/static/js/emotion-presets.js'),'utf8');
const {EMOTION_TO_VRM,resolveEmotion}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const model=fs.readFileSync(path.join(root,'character/Mocha.vrm'));
const gltf=JSON.parse(model.subarray(20,20+model.readUInt32LE(12)));
const expressions=gltf.extensions.VRMC_vrm.expressions;
const recipes=JSON.parse(fs.readFileSync(path.join(pack,'expression_recipes.json')));
assert.deepEqual(expressions.preset.happy,recipes.original_expressions.preset.happy);
assert.ok(expressions.custom.smile);
assert.notDeepEqual(expressions.custom.smile.morphTargetBinds,expressions.preset.happy.morphTargetBinds);
const known={...expressions.preset,...expressions.custom},values={aa:.4,ih:.2};
const vrm={expressionManager:{getExpression:n=>known[n],setValue(n,v){assert.ok(known[n],n);values[n]=v;}}};
for(const id of Object.keys(EMOTION_TO_VRM))assert.ok(known[resolveEmotion(id,vrm).preset],id);
const original={expressionManager:{getExpression:n=>expressions.preset[n]}};
for(const [id,e]of Object.entries(EMOTION_TO_VRM))if(e.fallback)assert.equal(resolveEmotion(id,original),EMOTION_TO_VRM[e.fallback]);
const renderer=fs.readFileSync(path.join(root,'web/static/js/vrm-renderer.js'),'utf8');
const fn=renderer.match(/function applyEmotion\(emotionId\) \{[\s\S]*?\n\}/)[0];
const context={vrm,resolveEmotion,currentEmotionPreset:null};
vm.createContext(context);vm.runInContext(fn,context);
context.applyEmotion('playful_wink');assert.equal(values.playful_wink,1);
context.applyEmotion('warm_smile');assert.equal(values.playful_wink,0);assert.equal(values.warm_smile,1);
context.applyEmotion('happy');assert.equal(values.warm_smile,0);assert.equal(values.happy,.8);
context.applyEmotion('smile');assert.equal(values.happy,0);assert.equal(values.smile,.8);
context.applyEmotion('happy');assert.equal(values.smile,0);assert.equal(values.happy,.8);
context.applyEmotion('unknown');assert.equal(values.happy,0);
assert.equal(values.aa,.4);assert.equal(values.ih,.2);
const report={status:'PASS',emotionChoices:Object.keys(EMOTION_TO_VRM).length,customPresets:Object.keys(expressions.custom).length,originalHappyPreserved:true,happyAndSmileDistinct:true,bidirectionalSwitchClearsPrevious:true,avatarFallback:true,previousEmotionCleared:true,visemeWeightsPreserved:true};
fs.writeFileSync(path.join(pack,'expression_runtime_validation.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report));
